# Generated by Django 2.2.4 on 2020-04-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dojo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dojo_ninjas_app.Dojo')),
            ],
        ),
        migrations.DeleteModel(
            name='Ninjas',
        ),
    ]
